import { addIcons } from 'ionicons';
import { 
    home, 
    key, 
    location, 
    restaurant, 
    time, 
    calendar, 
    documentText, 
    information, 
    newspaper, 
    menu, 
    logIn, 
    logOut, 
    compass, 
    list, 
    person, 
    lockOpen, 
    lockClosed, 
    trophy, 
    podium, 
    checkmarkCircle, 
    statsChart,
    helpCircle,
} from 'ionicons/icons';

export function registerIcons() {
    addIcons({
        'key': key,
        'location': location,
        'restaurant': restaurant,
        'time': time,
        'document-text': documentText,
        'information': information,
        'home': home,
        'menu': menu,
        'login': logIn,
        'logout': logOut,
        'list': list,
        'person': person,
        'compass': compass,
        'calendar': calendar,
        'newspaper': newspaper,
        'lock-open': lockOpen,
        'lock-closed': lockClosed,
        'trophy' : trophy, 
        'stats-chart': statsChart,
        'podium' : podium,
        'checkmark-circle' : checkmarkCircle,
        'help-circle' : helpCircle,
    });
}